/**
 * 功法系统相关常量
 */

import { RealmType, CultivationArt, BattleSkill } from '../types';

export const CULTIVATION_ARTS: CultivationArt[] = [
  {
    id: 'art-basic-breath',
    name: '吐纳法',
    type: 'mental',
    grade: '黄',
    description: '基础的呼吸吐纳之术，微弱提升修炼速度。',
    realmRequirement: RealmType.QiRefining,
    cost: 0,
    effects: { expRate: 0.1 },
  },
  {
    id: 'art-iron-skin',
    name: '铁皮功',
    type: 'body',
    grade: '黄',
    description: '锤炼皮肉，使其坚如凡铁。永久提升防御。',
    realmRequirement: RealmType.QiRefining,
    cost: 50,
    effects: { defense: 5, hp: 20 },
  },
  {
    id: 'art-spirit-cloud',
    name: '青云诀',
    type: 'mental',
    grade: '黄',
    description: '青云宗入门心法，吸纳灵气如云雾缭绕。',
    realmRequirement: RealmType.QiRefining,
    cost: 100,
    sectId: 'sect-cloud', // 青云宗专属
    effects: { expRate: 0.25, attack: 5 },
  },
  {
    id: 'art-fiery-fist',
    name: '烈火拳',
    type: 'body',
    grade: '玄',
    description: '将灵气转化为烈火附着于双拳。大幅提升攻击力。',
    realmRequirement: RealmType.Foundation,
    cost: 300,
    spiritualRoot: 'fire',
    effects: { attack: 30 },
  },
  {
    id: 'art-jade-bone',
    name: '玉骨功',
    type: 'body',
    grade: '玄',
    description: '锻骨如玉，百毒不侵。大幅提升气血与防御。',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    spiritualRoot: 'earth',
    effects: { defense: 20, hp: 100 },
  },
  {
    id: 'art-pure-yang',
    name: '纯阳无极功',
    type: 'mental',
    grade: '地',
    description: '至刚至阳的高深心法，修炼速度极快。',
    realmRequirement: RealmType.GoldenCore,
    cost: 2000,
    spiritualRoot: 'fire',
    effects: { expRate: 0.5, attack: 50 },
  },
  {
    id: 'art-thunder-sword',
    name: '天雷剑诀',
    type: 'body',
    grade: '地',
    description: '引九天神雷入剑，威力绝伦，若是肉身不够强横恐遭反噬。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3000,
    spiritualRoot: 'metal',
    effects: { attack: 150 },
  },
  {
    id: 'art-immortal-life',
    name: '长生诀',
    type: 'mental',
    grade: '天',
    description: '上古木系神功，生生不息，气血悠长。',
    realmRequirement: RealmType.NascentSoul,
    cost: 8000,
    spiritualRoot: 'wood',
    effects: { expRate: 0.6, hp: 2000 },
  },
  {
    id: 'art-void-body',
    name: '虚空霸体',
    type: 'body',
    grade: '天',
    description: '炼化虚空之力入体，肉身成圣。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 20000,
    effects: { defense: 500, attack: 500, hp: 5000 },
  },
  {
    id: 'art-wind-step',
    name: '御风步',
    type: 'body',
    grade: '黄',
    description: '身法如风，行动迅捷。提升攻击和速度。',
    realmRequirement: RealmType.QiRefining,
    cost: 80,
    effects: { attack: 8 },
  },
  {
    id: 'art-water-mirror',
    name: '水镜心法',
    type: 'mental',
    grade: '玄',
    description: '心如止水，明镜高悬。提升修炼速度和防御。',
    realmRequirement: RealmType.Foundation,
    cost: 400,
    spiritualRoot: 'water',
    effects: { expRate: 0.3, defense: 15 },
  },
  {
    id: 'art-earth-shield',
    name: '厚土护体',
    type: 'body',
    grade: '玄',
    description: '引大地之力护体，防御力极强。',
    realmRequirement: RealmType.Foundation,
    cost: 600,
    spiritualRoot: 'earth',
    effects: { defense: 40, hp: 150 },
  },
  {
    id: 'art-ice-soul',
    name: '冰心诀',
    type: 'mental',
    grade: '地',
    description: '心如寒冰，不为外物所动。大幅提升修炼速度。',
    realmRequirement: RealmType.GoldenCore,
    cost: 2500,
    effects: { expRate: 0.6, defense: 30 },
  },
  {
    id: 'art-dragon-fist',
    name: '龙拳',
    type: 'body',
    grade: '地',
    description: '拳如真龙，威力无穷。大幅提升攻击力。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3500,
    effects: { attack: 200 },
  },
  {
    id: 'art-phoenix-rebirth',
    name: '凤凰涅槃功',
    type: 'mental',
    grade: '天',
    description: '如凤凰涅槃，每次突破都能获得巨大提升。',
    realmRequirement: RealmType.NascentSoul,
    cost: 10000,
    effects: { expRate: 0.7, hp: 3000, attack: 100 },
  },
  {
    id: 'art-star-destruction',
    name: '星辰破灭诀',
    type: 'body',
    grade: '天',
    description: '引星辰之力，破灭万物。攻击力达到极致。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 25000,
    effects: { attack: 1000, defense: 200 },
  },
  {
    id: 'art-universe-devour',
    name: '吞天噬地',
    type: 'mental',
    grade: '天',
    description: '吞噬天地灵气，修炼速度达到极致。',
    realmRequirement: RealmType.DaoCombining,
    cost: 50000,
    effects: { expRate: 1.0, attack: 500, defense: 500, hp: 10000 },
  },
  // 新增20种功法
  {
    id: 'art-wooden-body',
    name: '木身功',
    type: 'body',
    grade: '黄',
    description: '基础炼体功法，如古木般坚韧。',
    realmRequirement: RealmType.QiRefining,
    cost: 60,
    effects: { defense: 8, hp: 30 },
  },
  {
    id: 'art-golden-armor',
    name: '金甲功',
    type: 'body',
    grade: '黄',
    description: '将灵气化作金甲护体，防御力不俗。',
    realmRequirement: RealmType.QiRefining,
    cost: 120,
    effects: { defense: 15, hp: 40 },
  },
  {
    id: 'art-moonlight-refine',
    name: '月华淬炼诀',
    type: 'mental',
    grade: '黄',
    description: '吸收月华之力，提升修炼速度。',
    realmRequirement: RealmType.QiRefining,
    cost: 150,
    effects: { expRate: 0.2, spirit: 5 },
  },
  {
    id: 'art-swift-shadow',
    name: '疾影步',
    type: 'body',
    grade: '黄',
    description: '身法如影，速度极快。',
    realmRequirement: RealmType.QiRefining,
    cost: 100,
    effects: { speed: 10, attack: 5 },
  },
  {
    id: 'art-flame-palm',
    name: '炎掌',
    type: 'body',
    grade: '玄',
    description: '掌中带火，焚尽万物。',
    realmRequirement: RealmType.Foundation,
    cost: 350,
    effects: { attack: 40, defense: 5 },
  },
  {
    id: 'art-frost-breath',
    name: '寒冰吐息',
    type: 'mental',
    grade: '玄',
    description: '冰系心法，修炼时如临寒潭。',
    realmRequirement: RealmType.Foundation,
    cost: 450,
    effects: { expRate: 0.35, defense: 20 },
  },
  {
    id: 'art-iron-fist',
    name: '铁拳术',
    type: 'body',
    grade: '玄',
    description: '双拳如铁，刚猛无比。',
    realmRequirement: RealmType.Foundation,
    cost: 550,
    effects: { attack: 50, hp: 80 },
  },
  {
    id: 'art-cloud-dance',
    name: '云舞身法',
    type: 'body',
    grade: '玄',
    description: '身法飘逸，如云中起舞。',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    effects: { speed: 20, defense: 15 },
  },
  {
    id: 'art-storm-heart',
    name: '风暴之心',
    type: 'mental',
    grade: '玄',
    description: '心法狂暴如风暴，修炼速度惊人。',
    realmRequirement: RealmType.Foundation,
    cost: 700,
    effects: { expRate: 0.4, attack: 20 },
  },
  {
    id: 'art-jade-armor',
    name: '玉甲护体',
    type: 'body',
    grade: '玄',
    description: '炼体至玉质，防御力大增。',
    realmRequirement: RealmType.Foundation,
    cost: 800,
    effects: { defense: 50, hp: 200 },
  },
  {
    id: 'art-sun-flame',
    name: '太阳真火',
    type: 'mental',
    grade: '地',
    description: '引太阳真火入体，至阳至刚。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3000,
    effects: { expRate: 0.55, attack: 80, hp: 300 },
  },
  {
    id: 'art-dark-sword',
    name: '幽冥剑法',
    type: 'body',
    grade: '地',
    description: '剑法诡异，伤人于无形。',
    realmRequirement: RealmType.GoldenCore,
    cost: 4000,
    effects: { attack: 180, speed: 30 },
  },
  {
    id: 'art-celestial-body',
    name: '天元体',
    type: 'body',
    grade: '地',
    description: '炼体至天元，肉身强横。',
    realmRequirement: RealmType.GoldenCore,
    cost: 4500,
    effects: { defense: 120, hp: 500, attack: 100 },
  },
  {
    id: 'art-starlight-gather',
    name: '聚星诀',
    type: 'mental',
    grade: '地',
    description: '聚集星辰之力，修炼事半功倍。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3800,
    effects: { expRate: 0.65, spirit: 50 },
  },
  {
    id: 'art-soul-forge',
    name: '炼魂诀',
    type: 'mental',
    grade: '地',
    description: '淬炼神魂，神识大增。',
    realmRequirement: RealmType.GoldenCore,
    cost: 4200,
    effects: { expRate: 0.6, spirit: 800, defense: 400 },
  },
  {
    id: 'art-divine-dragon',
    name: '真龙诀',
    type: 'mental',
    grade: '天',
    description: '真龙传承心法，威震天地。',
    realmRequirement: RealmType.NascentSoul,
    cost: 12000,
    effects: { expRate: 0.75, attack: 1500, hp: 2500 },
  },
  {
    id: 'art-void-step',
    name: '虚空步',
    type: 'body',
    grade: '天',
    description: '穿梭虚空，身法超绝。',
    realmRequirement: RealmType.NascentSoul,
    cost: 15000,
    effects: { speed: 3000, attack: 1200, defense: 80 },
  },
  {
    id: 'art-chaos-body',
    name: '混沌体',
    type: 'body',
    grade: '天',
    description: '炼化混沌之力，肉身成圣。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 30000,
    effects: { defense: 8000, attack: 6000, hp: 80000 },
  },
  {
    id: 'art-dao-heart',
    name: '道心诀',
    type: 'mental',
    grade: '天',
    description: '领悟大道之心，修炼速度登峰造极。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 35000,
    effects: { expRate: 0.9, spirit: 2000, attack: 3000, defense: 2500 },
  },
  {
    id: 'art-immortal-awakening',
    name: '仙醒诀',
    type: 'mental',
    grade: '天',
    description: '觉醒仙人之力，超越凡俗。',
    realmRequirement: RealmType.DaoCombining,
    cost: 60000,
    spiritualRoot: 'fire',
    effects: { expRate: 1.0, attack: 800, defense: 600, hp: 5000, spirit: 500 }, // 平衡：修炼速度100%，属性提升合理
  },
  // 新增五行功法
  {
    id: 'art-golden-sword',
    name: '金剑诀',
    type: 'body',
    grade: '黄',
    description: '金系剑法，锋芒毕露。',
    realmRequirement: RealmType.QiRefining,
    cost: 90,
    spiritualRoot: 'metal',
    effects: { attack: 12, defense: 3 },
  },
  {
    id: 'art-wooden-heart',
    name: '木心诀',
    type: 'mental',
    grade: '黄',
    description: '木系心法，生机勃勃。',
    realmRequirement: RealmType.QiRefining,
    cost: 70,
    spiritualRoot: 'wood',
    effects: { expRate: 0.15, hp: 25 },
  },
  {
    id: 'art-water-flow',
    name: '流水诀',
    type: 'mental',
    grade: '黄',
    description: '水系心法，柔中带刚。',
    realmRequirement: RealmType.QiRefining,
    cost: 85,
    spiritualRoot: 'water',
    effects: { expRate: 0.18, spirit: 4 },
  },
  {
    id: 'art-flame-body',
    name: '火体功',
    type: 'body',
    grade: '黄',
    description: '火系炼体，刚猛霸道。',
    realmRequirement: RealmType.QiRefining,
    cost: 95,
    spiritualRoot: 'fire',
    effects: { attack: 10, speed: 5 },
  },
  {
    id: 'art-earth-core',
    name: '土核功',
    type: 'body',
    grade: '黄',
    description: '土系炼体，厚重沉稳。',
    realmRequirement: RealmType.QiRefining,
    cost: 75,
    spiritualRoot: 'earth',
    effects: { defense: 10, hp: 35 },
  },
  {
    id: 'art-golden-protection',
    name: '金甲护体',
    type: 'body',
    grade: '玄',
    description: '金系防御功法，坚不可摧。',
    realmRequirement: RealmType.Foundation,
    cost: 650,
    spiritualRoot: 'metal',
    effects: { defense: 55, attack: 25 },
  },
  {
    id: 'art-wooden-rebirth',
    name: '木生诀',
    type: 'mental',
    grade: '玄',
    description: '木系恢复心法，生生不息。',
    realmRequirement: RealmType.Foundation,
    cost: 550,
    spiritualRoot: 'wood',
    effects: { expRate: 0.35, hp: 180, defense: 10 },
  },
  {
    id: 'art-ice-spirit',
    name: '冰魄诀',
    type: 'mental',
    grade: '玄',
    description: '水系变异心法，冰寒刺骨。',
    realmRequirement: RealmType.Foundation,
    cost: 750,
    spiritualRoot: 'water',
    effects: { expRate: 0.38, spirit: 30, defense: 25 },
  },
  {
    id: 'art-sun-fire',
    name: '太阳真火诀',
    type: 'mental',
    grade: '地',
    description: '火系至高心法，如太阳般炽热。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3500,
    spiritualRoot: 'fire',
    effects: { expRate: 0.58, attack: 90, hp: 400 },
  },
  {
    id: 'art-earth-mountain',
    name: '山岳功',
    type: 'body',
    grade: '地',
    description: '土系炼体至境，如山岳般厚重。',
    realmRequirement: RealmType.GoldenCore,
    cost: 4000,
    spiritualRoot: 'earth',
    effects: { defense: 150, hp: 600, attack: 60 },
  },
  {
    id: 'art-golden-dragon',
    name: '金龙诀',
    type: 'body',
    grade: '地',
    description: '金系至高功法，如金龙般威猛。',
    realmRequirement: RealmType.GoldenCore,
    cost: 4200,
    spiritualRoot: 'metal',
    effects: { attack: 220, defense: 80, speed: 40 },
  },
  {
    id: 'art-wood-immortal',
    name: '木仙诀',
    type: 'mental',
    grade: '天',
    description: '木系仙级心法，与天地同寿。',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    spiritualRoot: 'wood',
    effects: { expRate: 0.7, hp: 3000, defense: 200 },
  },
  {
    id: 'art-ocean-heart',
    name: '海心诀',
    type: 'mental',
    grade: '天',
    description: '水系仙级心法，如海洋般深邃。',
    realmRequirement: RealmType.NascentSoul,
    cost: 13000,
    spiritualRoot: 'water',
    effects: { expRate: 0.68, spirit: 1200, defense: 300 },
  },
  {
    id: 'art-phoenix-fire',
    name: '凤凰真火',
    type: 'mental',
    grade: '天',
    description: '火系仙级心法，如凤凰涅槃。',
    realmRequirement: RealmType.NascentSoul,
    cost: 14000,
    spiritualRoot: 'fire',
    effects: { expRate: 0.72, attack: 1800, hp: 2800 },
  },
  {
    id: 'art-earth-immortal',
    name: '土仙体',
    type: 'body',
    grade: '天',
    description: '土系仙级炼体，与大地同源。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 28000,
    spiritualRoot: 'earth',
    effects: { defense: 1500, hp: 15000, attack: 800 }, // 平衡：降低到合理范围
  },
  {
    id: 'art-golden-immortal',
    name: '金仙剑',
    type: 'body',
    grade: '天',
    description: '金系仙级剑法，斩断一切。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 32000,
    spiritualRoot: 'metal',
    effects: { attack: 1200, defense: 400, speed: 200 }, // 平衡：提升到合理范围（化神期天级功法）
  },
  {
    id: 'art-five-elements',
    name: '五行归一',
    type: 'mental',
    grade: '天',
    description: '融合五行之力，达到修炼的极致。',
    realmRequirement: RealmType.DaoCombining,
    cost: 70000,
    effects: { expRate: 1.0, attack: 2000, defense: 1500, hp: 10000, spirit: 1200 }, // 平衡：降低到合理范围
  },
  // ==================== 新增攻击类功法 ====================
  // 黄级攻击功法（炼气期）
  {
    id: 'art-sharp-blade',
    name: '锐刃诀',
    type: 'body',
    grade: '黄',
    description: '将灵气凝聚为锐利刀刃，提升攻击力。',
    realmRequirement: RealmType.QiRefining,
    cost: 70,
    effects: { attack: 15 },
  },
  {
    id: 'art-thunder-palm',
    name: '雷掌',
    type: 'body',
    grade: '黄',
    description: '掌中带雷，威力不俗。',
    realmRequirement: RealmType.QiRefining,
    cost: 110,
    spiritualRoot: 'metal',
    effects: { attack: 18, speed: 3 },
  },
  {
    id: 'art-wind-blade',
    name: '风刃术',
    type: 'body',
    grade: '黄',
    description: '以风为刃，迅疾如电。',
    realmRequirement: RealmType.QiRefining,
    cost: 85,
    effects: { attack: 14, speed: 8 },
  },
  {
    id: 'art-ice-sword',
    name: '寒冰剑',
    type: 'body',
    grade: '黄',
    description: '冰系剑法，寒气逼人。',
    realmRequirement: RealmType.QiRefining,
    cost: 95,
    spiritualRoot: 'water',
    effects: { attack: 16, defense: 4 },
  },
  // 玄级攻击功法（筑基期）
  {
    id: 'art-blood-blade',
    name: '血刃诀',
    type: 'body',
    grade: '玄',
    description: '以血为引，凝聚血刃，攻击力极强。',
    realmRequirement: RealmType.Foundation,
    cost: 400,
    effects: { attack: 60 },
  },
  {
    id: 'art-lightning-strike',
    name: '雷霆一击',
    type: 'body',
    grade: '玄',
    description: '引天雷之力，一击必杀。',
    realmRequirement: RealmType.Foundation,
    cost: 450,
    spiritualRoot: 'metal',
    effects: { attack: 70, speed: 15 },
  },
  {
    id: 'art-demon-fist',
    name: '魔拳',
    type: 'body',
    grade: '玄',
    description: '魔道拳法，威力霸道。',
    realmRequirement: RealmType.Foundation,
    cost: 500,
    effects: { attack: 65, hp: 50 },
  },
  {
    id: 'art-frost-sword',
    name: '霜寒剑法',
    type: 'body',
    grade: '玄',
    description: '冰系剑法，剑出如霜。',
    realmRequirement: RealmType.Foundation,
    cost: 480,
    spiritualRoot: 'water',
    effects: { attack: 55, defense: 20 },
  },
  {
    id: 'art-wind-sword',
    name: '疾风剑',
    type: 'body',
    grade: '玄',
    description: '剑如疾风，快如闪电。',
    realmRequirement: RealmType.Foundation,
    cost: 420,
    effects: { attack: 45, speed: 25 },
  },
  {
    id: 'art-fire-blade',
    name: '烈焰刀',
    type: 'body',
    grade: '玄',
    description: '火系刀法，刀出如烈焰。',
    realmRequirement: RealmType.Foundation,
    cost: 380,
    spiritualRoot: 'fire',
    effects: { attack: 50, hp: 30 },
  },
  // 地级攻击功法（金丹期）
  {
    id: 'art-sword-intent',
    name: '剑意诀',
    type: 'body',
    grade: '地',
    description: '领悟剑意，人剑合一，攻击力大增。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3200,
    effects: { attack: 250 },
  },
  {
    id: 'art-killing-intent',
    name: '杀意诀',
    type: 'body',
    grade: '地',
    description: '凝聚杀意，出手必杀。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3600,
    effects: { attack: 280, speed: 50 },
  },
  {
    id: 'art-divine-sword',
    name: '神剑诀',
    type: 'body',
    grade: '地',
    description: '神级剑法，威力绝伦。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3800,
    spiritualRoot: 'metal',
    effects: { attack: 300, defense: 100 },
  },
  {
    id: 'art-phoenix-blade',
    name: '凤凰刀',
    type: 'body',
    grade: '地',
    description: '如凤凰展翅，刀法华丽而致命。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3400,
    spiritualRoot: 'fire',
    effects: { attack: 260, hp: 400 },
  },
  {
    id: 'art-dragon-claw',
    name: '龙爪功',
    type: 'body',
    grade: '地',
    description: '如真龙之爪，撕裂一切。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3700,
    effects: { attack: 270, defense: 60 },
  },
  {
    id: 'art-void-sword',
    name: '虚空剑',
    type: 'body',
    grade: '地',
    description: '剑破虚空，无物不斩。',
    realmRequirement: RealmType.GoldenCore,
    cost: 3900,
    effects: { attack: 320, speed: 60 },
  },
  // 天级攻击功法（元婴期及以上）
  {
    id: 'art-immortal-sword',
    name: '斩仙剑诀',
    type: 'body',
    grade: '天',
    description: '仙级剑法，一剑破万法。',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    effects: { attack: 1800, defense: 500, speed: 100 },
  },
  {
    id: 'art-lu-xian-sword',
    name: '戮仙剑诀',
    type: 'body',
    grade: '天',
    description: '仙级剑法，一剑破万法。',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    effects: { attack: 1800, defense: 300, speed: 1000 },
  },
  {
    id: 'art-xian-xian-sword',
    name: '陷仙剑诀',
    type: 'body',
    grade: '天',
    description: '仙级剑法，一剑破万法。',
    realmRequirement: RealmType.NascentSoul,
    cost: 11000,
    effects: { attack: 1800, defense: 3000, speed: 100 },
  },
  {
    id: 'art-divine-destruction',
    name: '诛仙剑诀',
    type: 'body',
    grade: '天',
    description: '神级攻击功法，可灭神斩仙。',
    realmRequirement: RealmType.NascentSoul,
    cost: 13000,
    effects: { attack: 1800, speed: 200, spirit: 2000 },
  },
  {
    id: 'art-celestial-blade',
    name: '开天',
    type: 'body',
    grade: '天',
    description: '天级刀法，一刀断天地。',
    realmRequirement: RealmType.NascentSoul,
    cost: 12000,
    spiritualRoot: 'metal',
    effects: { attack: 1600, defense: 250, speed: 150 },
  },
  {
    id: 'art-demon-god-fist',
    name: '魔神道音',
    type: 'body',
    grade: '天',
    description: '魔道至高拳法，一拳可破天。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 28000,
    effects: { attack: 5000, hp: 3000 },
  },
  {
    id: 'art-universe-sword',
    name: '五行生灭剑',
    type: 'body',
    grade: '天',
    description: '剑法达到极致，可斩断宇宙。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 30000,
    effects: { attack: 6000, defense: 1500, speed: 1000 },
  },
  {
    id: 'art-absolute-destruction',
    name: '归墟',
    type: 'body',
    grade: '天',
    description: '毁灭一切的力量，攻击力达到极致。',
    realmRequirement: RealmType.DaoCombining,
    cost: 60000,
    effects: { attack: 12000, defense: 3000, speed: 2000 },
  },
  {
    id: 'art-heaven-justice',
    name: '天罡正法',
    type: 'body',
    grade: '天',
    description: '天罡之魄传授的无上秘法，蕴含天地间最纯粹的阳气。大幅提升攻击和气血。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 80000,
    isHeavenEarthSoulArt: true,  // 标记为天地之魄功法
    bossId: 'boss_001',  // 对应天罡之魄
    effects: { attack: 15000, defense: 5000, hp: 30000, spirit: 8000, physique: 5000 },
  },
  {
    id: 'art-earth-evil',
    name: '地煞冥诀',
    type: 'body',
    grade: '天',
    description: '地煞之魄传授的无上秘法，蕴含大地深处的阴煞之气。大幅提升防御和气血。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 80000,
    isHeavenEarthSoulArt: true,  // 标记为天地之魄功法
    bossId: 'boss_002',  // 对应地煞之魄
    effects: { attack: 8000, defense: 15000, hp: 40000, spirit: 6000, physique: 8000 },
  },
  {
    id: 'art-yin-yang-reincarnation',
    name: '阴阳轮回诀',
    type: 'body',
    grade: '天',
    description: '阴阳之魄传授的无上秘法，融合阴阳二气。全面提升所有属性。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 100000,
    isHeavenEarthSoulArt: true,  // 标记为天地之魄功法
    bossId: 'boss_003',  // 对应阴阳之魄
    effects: { attack: 12000, defense: 12000, hp: 50000, spirit: 10000, physique: 10000, speed: 8000 },
  },
  {
    id: 'art-chaos-primal',
    name: '混沌归元功',
    type: 'body',
    grade: '天',
    description: '混沌之魄传授的无上秘法，混沌初开时的原始力量。属性提升达到极致。',
    realmRequirement: RealmType.SpiritSevering,
    cost: 150000,
    isHeavenEarthSoulArt: true,  // 标记为天地之魄功法
    bossId: 'boss_004',  // 对应混沌之魄
    effects: { attack: 20000, defense: 15000, hp: 80000, spirit: 15000, physique: 12000, speed: 10000 },
  },
];

// 功法战斗技能配置
export const CULTIVATION_ART_BATTLE_SKILLS: Record<string, BattleSkill[]> = {
  // 天雷剑诀 - 攻击技能
  'art-thunder-sword': [
    {
      id: 'skill-thunder-sword',
      name: '天雷剑诀',
      description: '引九天神雷入剑，对敌人造成大量法术伤害，有较高暴击率。',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-thunder-sword',
      effects: [],
      cost: { mana: 95 }, // 地品攻击技能,消耗从30提升至95
      cooldown: 0,
      maxCooldown: 2,
      target: 'enemy',
      damage: {
        base: 70, // 基础伤害从50提升至70
        multiplier: 1.8, // 伤害倍率从1.5提升至1.8
        type: 'magical', // 法术伤害（基于神识）
        critChance: 0.30, // 暴击率从0.25提升至0.30
        critMultiplier: 2.2, // 暴击倍率从2.0提升至2.2
      },
    },
  ],
  // 长生诀 - 治疗技能
  'art-immortal-life': [
    {
      id: 'skill-immortal-heal',
      name: '长生回春',
      description: '运转长生诀，恢复大量气血。',
      type: 'heal',
      source: 'cultivation_art',
      sourceId: 'art-immortal-life',
      effects: [],
      cost: { mana: 110 }, // 天品治疗技能,消耗从25大幅提升至110
      cooldown: 0,
      maxCooldown: 3,
      target: 'self',
      heal: {
        base: 150, // 基础治疗从100提升至150
        multiplier: 0.25, // 治疗倍率从0.2提升至0.25
      },
    },
  ],
  // 烈火拳 - 攻击技能
  'art-fiery-fist': [
    {
      id: 'skill-fiery-fist',
      name: '烈火拳',
      description: '将灵气转化为烈火附着于双拳，造成物理伤害并可能灼烧敌人。',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-fiery-fist',
      effects: [
        {
          type: 'debuff',
          target: 'enemy',
          debuff: {
            id: 'burn',
            name: '灼烧',
            type: 'burn',
            value: 15, // 灼烧伤害从10提升至15
            duration: 2,
            source: 'skill-fiery-fist',
            description: '每回合受到火焰伤害',
          },
        },
      ],
      cost: { mana: 55 }, // 玄品攻击技能,消耗从20提升至55
      cooldown: 0,
      maxCooldown: 2,
      target: 'enemy',
      damage: {
        base: 45, // 基础伤害从30提升至45
        multiplier: 1.35, // 伤害倍率从1.2提升至1.35
        type: 'physical',
        critChance: 0.20, // 暴击率从0.15提升至0.20
        critMultiplier: 1.95, // 暴击倍率从1.8提升至1.95
      },
    },
  ],
  // 纯阳无极功 - 被动效果（在战斗初始化时应用）
  'art-pure-yang': [
    {
      id: 'skill-pure-yang-buff',
      name: '纯阳护体',
      description: '纯阳无极功的被动效果，提升攻击力和暴击率。',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-pure-yang',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'pure-yang-attack',
            name: '纯阳之力',
            type: 'attack',
            value: 0.15, // 15%攻击力提升
            duration: -1, // 永久（战斗期间）
            source: 'art-pure-yang',
            description: '攻击力提升15%',
          },
        },
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'pure-yang-crit',
            name: '纯阳暴击',
            type: 'crit',
            value: 0.1, // 10%暴击率提升
            duration: -1,
            source: 'art-pure-yang',
            description: '暴击率提升10%',
          },
        },
      ],
      cost: {},
      cooldown: 0,
      maxCooldown: 0,
      target: 'self',
    },
  ],
  // 御风步 - 速度提升技能
  'art-wind-step': [
    {
      id: 'skill-wind-step',
      name: '御风步',
      description: '身法如风，提升速度，增加闪避和暴击率。',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-wind-step',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'wind-speed',
            name: '御风',
            type: 'speed',
            value: 0.2, // 20%速度提升
            duration: 3,
            source: 'art-wind-step',
            description: '速度提升20%，持续3回合',
          },
        },
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'wind-crit',
            name: '风之暴击',
            type: 'crit',
            value: 0.15, // 15%暴击率提升
            duration: 3,
            source: 'art-wind-step',
            description: '暴击率提升15%，持续3回合',
          },
        },
      ],
      cost: { mana: 35 }, // 黄品Buff技能,消耗从20提升至35
      cooldown: 0,
      maxCooldown: 3,
      target: 'self',
    },
  ],
  // 水镜心法 - 防御技能
  'art-water-mirror': [
    {
      id: 'skill-water-mirror',
      name: '水镜护体',
      description: '心如止水，明镜高悬，大幅提升防御力。',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-water-mirror',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'water-defense',
            name: '水镜',
            type: 'defense',
            value: 0.3, // 30%防御力提升
            duration: 3,
            source: 'art-water-mirror',
            description: '防御力提升30%，持续3回合',
          },
        },
      ],
      cost: { mana: 25 },
      cooldown: 0,
      maxCooldown: 3,
      target: 'self',
    },
  ],
  // 厚土护体 - 防御和护盾
  'art-earth-shield': [
    {
      id: 'skill-earth-shield',
      name: '厚土护体',
      description: '引大地之力护体，大幅提升防御并形成护盾。',
      type: 'buff',
      source: 'cultivation_art',
      sourceId: 'art-earth-shield',
      effects: [
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'earth-defense',
            name: '厚土',
            type: 'defense',
            value: 0.4, // 40%防御力提升
            duration: 4,
            source: 'art-earth-shield',
            description: '防御力提升40%，持续4回合',
          },
        },
        {
          type: 'buff',
          target: 'self',
          buff: {
            id: 'earth-shield',
            name: '大地护盾',
            type: 'shield',
            value: 200, // 护盾值
            duration: 4,
            source: 'art-earth-shield',
            description: '获得200点护盾，持续4回合',
          },
        },
      ],
      cost: { mana: 30 },
      cooldown: 0,
      maxCooldown: 4,
      target: 'self',
    },
  ],
  // 龙拳 - 高伤害攻击技能
  'art-dragon-fist': [
    {
      id: 'skill-dragon-fist',
      name: '龙拳',
      description: '拳如真龙，威力无穷，造成大量物理伤害。',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-dragon-fist',
      effects: [],
      cost: { mana: 35 },
      cooldown: 0,
      maxCooldown: 3,
      target: 'enemy',
      damage: {
        base: 80,
        multiplier: 1.8,
        type: 'physical',
        critChance: 0.2,
        critMultiplier: 2.2,
      },
    },
  ],
  // 星辰破灭诀 - 终极攻击技能
  'art-star-destruction': [
    {
      id: 'skill-star-destruction',
      name: '星辰破灭',
      description: '引星辰之力，破灭万物，造成巨额法术伤害。',
      type: 'attack',
      source: 'cultivation_art',
      sourceId: 'art-star-destruction',
      effects: [],
      cost: { mana: 50 },
      cooldown: 0,
      maxCooldown: 5,
      target: 'enemy',
      damage: {
        base: 150,
        multiplier: 2.5,
        type: 'magical',
        critChance: 0.3,
        critMultiplier: 2.5,
      },
    },
  ],
};
