/**
 * 秘境系统相关常量
 */

import { RealmType, SecretRealm } from '../types';

export const SECRET_REALMS: SecretRealm[] = [
  {
    id: 'realm-beast-mountain',
    name: '万兽山脉',
    description:
      '外围相对安全，深处盘踞着可怕的妖兽。适合炼气、筑基期修士历练。',
    minRealm: RealmType.QiRefining,
    cost: 80,
    riskLevel: '中',
    drops: ['妖兽材料', '稀有草药', '攻击法器'],
  },
  {
    id: 'realm-ancient-tomb',
    name: '上古剑冢',
    description: '传说中上古剑修的埋骨之地，剑气纵横。非筑基期不可入。',
    minRealm: RealmType.Foundation,
    cost: 300,
    riskLevel: '高',
    drops: ['剑修功法', '残破灵宝', '剑意草'],
  },
  {
    id: 'realm-thunder-purgatory',
    name: '雷罚炼狱',
    description: '终年雷霆不息，稍有不慎便会灰飞烟灭。',
    minRealm: RealmType.GoldenCore,
    cost: 800,
    riskLevel: '极度危险',
    drops: ['雷属性至宝', '仙品丹药材料', '天阶功法'],
  },
  {
    id: 'realm-immortal-garden',
    name: '仙灵秘境',
    description: '仙灵之气浓郁，适合修炼，相对安全。适合初入仙途的修士。',
    minRealm: RealmType.QiRefining,
    cost: 50,
    riskLevel: '低',
    drops: ['聚灵草', '普通丹药', '基础功法'],
  },
  {
    id: 'realm-star-ruins',
    name: '星辰遗迹',
    description: '星辰之力汇聚，灵气充沛，但需小心守护妖兽。',
    minRealm: RealmType.QiRefining,
    cost: 60,
    riskLevel: '低',
    drops: ['星辰石', '灵草', '防御法器'],
  },
  {
    id: 'realm-ice-domain',
    name: '冰封雪域',
    description: '冰天雪地，寒风刺骨，但蕴藏着珍贵的冰属性宝物。',
    minRealm: RealmType.Foundation,
    cost: 250,
    riskLevel: '中',
    drops: ['冰晶', '寒属性灵草', '冰系功法'],
  },
  {
    id: 'realm-dragon-tomb',
    name: '龙族古墓',
    description: '龙族遗迹，蕴藏着龙族传承，但守护力量不弱。',
    minRealm: RealmType.Foundation,
    cost: 400,
    riskLevel: '中',
    drops: ['龙鳞', '龙血草', '龙族传承'],
  },
  {
    id: 'realm-fire-lava',
    name: '天火熔岩',
    description: '地火喷涌，岩浆翻滚，火属性修士的圣地，但极端危险。',
    minRealm: RealmType.GoldenCore,
    cost: 600,
    riskLevel: '高',
    drops: ['火精', '熔岩之心', '火系至宝'],
  },
  {
    id: 'realm-poison-swamp',
    name: '毒瘴沼泽',
    description: '毒气弥漫，危险重重，但蕴藏着珍稀毒草和剧毒妖兽。',
    minRealm: RealmType.GoldenCore,
    cost: 700,
    riskLevel: '高',
    drops: ['毒草', '毒丹材料', '毒系功法'],
  },
  {
    id: 'realm-blood-sea',
    name: '血海魔渊',
    description: '魔气滔天，邪物横行，是正道修士的绝地，九死一生。',
    minRealm: RealmType.NascentSoul,
    cost: 1500,
    riskLevel: '极度危险',
    drops: ['魔血', '邪道功法', '魔器碎片'],
  },
  {
    id: 'realm-nine-hells',
    name: '九幽深渊',
    description: '九幽之地，死气沉沉，亡者的国度，生者禁入。',
    minRealm: RealmType.NascentSoul,
    cost: 1200,
    riskLevel: '极度危险',
    drops: ['死灵精华', '阴属性至宝', '鬼道传承'],
  },
  {
    id: 'realm-chaos-void',
    name: '混沌虚空',
    description: '混沌之力混乱，空间不稳定，随时可能被空间裂缝吞噬。',
    minRealm: RealmType.SpiritSevering,
    cost: 2000,
    riskLevel: '极度危险',
    drops: ['混沌石', '空间碎片', '虚空传承'],
  },
  {
    id: 'realm-god-demon-battlefield',
    name: '神魔战场',
    description: '上古神魔大战的遗迹，杀气冲天，怨灵遍地。',
    minRealm: RealmType.SpiritSevering,
    cost: 2500,
    riskLevel: '极度危险',
    drops: ['神魔遗物', '战魂精华', '上古传承'],
  },
  {
    id: 'realm-time-rift',
    name: '时光裂缝',
    description: '时间之力扭曲，过去未来交错，稍有不慎便会迷失其中。',
    minRealm: RealmType.GoldenCore,
    cost: 900,
    riskLevel: '高',
    drops: ['时光碎片', '时间之沙', '时空功法'],
  },
  {
    id: 'realm-phantom-cave',
    name: '幻境迷窟',
    description: '幻象丛生，真假难辨，考验修士的心智和意志。',
    minRealm: RealmType.Foundation,
    cost: 350,
    riskLevel: '中',
    drops: ['幻心草', '幻术功法', '迷魂符'],
  },
];
