/**
 * 商店系统相关常量
 * 包含所有商店定义和商店物品配置
 */

import { ShopType, ItemType, EquipmentSlot, RealmType, Shop } from '../types';

// --- 商店系统 ---

export const SHOPS: Shop[] = [
  {
    id: 'shop-village',
    name: '村庄杂货铺',
    type: ShopType.Village,
    description: '小村庄的杂货铺，主要售卖基础物品和低阶材料。',
    items: [
      {
        id: 'shop-herb-1',
        name: '止血草',
        type: ItemType.Herb,
        description: '常见的草药，用于治疗轻微外伤。',
        rarity: '普通',
        price: 10,
        sellPrice: 3,
        effect: { hp: 20 },
      },
      {
        id: 'shop-material-1',
        name: '炼器石',
        type: ItemType.Material,
        description: '用于强化法宝的基础材料。',
        rarity: '普通',
        price: 15,
        sellPrice: 5,
      },
      {
        id: 'shop-pill-1',
        name: '聚气丹',
        type: ItemType.Pill,
        description: '短时间内大幅提升修炼速度。',
        rarity: '普通',
        price: 30,
        sellPrice: 10,
        effect: { exp: 50 },
      },
      {
        id: 'shop-weapon-1',
        name: '木剑',
        type: ItemType.Weapon,
        description: '普通的木制剑，适合初学者。',
        rarity: '普通',
        price: 50,
        sellPrice: 15,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 3 },
      },
    ],
  },
  {
    id: 'shop-city',
    name: '城市商会',
    type: ShopType.City,
    description: '繁华城市的商会，商品种类丰富，品质较高。',
    items: [
      {
        id: 'shop-herb-2',
        name: '聚灵草',
        type: ItemType.Herb,
        description: '吸收天地灵气的草药，炼制聚气丹的主材。',
        rarity: '普通',
        price: 20,
        sellPrice: 7,
      },
      {
        id: 'shop-pill-2',
        name: '回春丹',
        type: ItemType.Pill,
        description: '疗伤圣药，大幅恢复气血。',
        rarity: '稀有',
        price: 100,
        sellPrice: 30,
        effect: { hp: 200 },
      },
      {
        id: 'shop-weapon-2',
        name: '精铁剑',
        type: ItemType.Weapon,
        description: '精铁打造的利剑，锋利无比。',
        rarity: '普通',
        price: 150,
        sellPrice: 45,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 10 },
      },
      {
        id: 'shop-armor-1',
        name: '布甲',
        type: ItemType.Armor,
        description: '普通的布制护甲，提供基础防护。',
        rarity: '普通',
        price: 120,
        sellPrice: 36,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 5, hp: 20 },
      },
      {
        id: 'shop-ring-1',
        name: '铜戒指',
        type: ItemType.Ring,
        description: '普通的铜制戒指，略微提升属性。',
        rarity: '普通',
        price: 80,
        sellPrice: 24,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Ring1,
        effect: { attack: 2, defense: 2 },
      },
      {
        id: 'shop-artifact-stone-normal',
        name: '凡品合成石',
        type: ItemType.ArtifactStone,
        description: '用于合成普通品质装备的合成石，可以融合两件凡铁级装备。',
        rarity: '普通',
        price: 500,
        sellPrice: 150,
      },
    ],
  },
  {
    id: 'shop-sect',
    name: '仙门宝库',
    type: ShopType.Sect,
    description: '仙门内部的宝库，只对门内弟子开放，售卖高阶物品。',
    items: [
      {
        id: 'shop-pill-3',
        name: '洗髓丹',
        type: ItemType.Pill,
        description: '易筋洗髓，脱胎换骨。永久增加少量最大生命值。',
        rarity: '稀有',
        price: 500,
        sellPrice: 150,
        effect: { hp: 50 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-artifact-stone-rare',
        name: '精品合成石',
        type: ItemType.ArtifactStone,
        description: '用于合成稀有品质装备的合成石，可以融合两件稀有级装备。',
        rarity: '稀有',
        price: 2000,
        sellPrice: 600,
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-artifact-stone-legendary',
        name: '极品合成石',
        type: ItemType.ArtifactStone,
        description: '用于合成传说品质装备的合成石，可以融合两件传说级装备。',
        rarity: '传说',
        price: 10000,
        sellPrice: 3000,
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-artifact-stone-immortal',
        name: '仙品合成石',
        type: ItemType.ArtifactStone,
        description: '用于合成仙品品质装备的合成石，可以融合两件仙品级装备。',
        rarity: '仙品',
        price: 50000,
        sellPrice: 20000,
        minRealm: RealmType.NascentSoul,
      },
      {
        id: 'shop-weapon-3',
        name: '青霜剑',
        type: ItemType.Weapon,
        description: '剑身泛着寒光，削铁如泥。',
        rarity: '稀有',
        price: 800,
        sellPrice: 240,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 15 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-armor-2',
        name: '青云道袍',
        type: ItemType.Armor,
        description: '青云宗内门弟子道袍，防御力不俗。',
        rarity: '稀有',
        price: 600,
        sellPrice: 180,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 15, hp: 50 },
        minRealm: RealmType.Foundation,
      },
      {
        id: 'shop-pill-4',
        name: '筑基丹',
        type: ItemType.Pill,
        description: '增加突破到筑基期的几率。服用后获得海量修为。',
        rarity: '传说',
        price: 2000,
        sellPrice: 600,
        effect: { exp: 500 },
        minRealm: RealmType.QiRefining,
      },
      {
        id: 'shop-weapon-legend',
        name: '天罡剑',
        type: ItemType.Weapon,
        description: '传说中的天罡剑，剑气纵横，威力无穷。',
        rarity: '传说',
        price: 5000,
        sellPrice: 1500,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 200, defense: 50 },
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-armor-legend',
        name: '龙鳞甲',
        type: ItemType.Armor,
        description: '用真龙鳞片打造的护甲，防御力极强。',
        rarity: '传说',
        price: 4000,
        sellPrice: 1200,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 150, hp: 500, attack: 30 },
        minRealm: RealmType.NascentSoul,
      },
      {
        id: 'shop-accessory-1',
        name: '护身符',
        type: ItemType.Accessory,
        description: '普通的护身符，提供基础防护。',
        rarity: '普通',
        price: 1000,
        sellPrice: 300,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Accessory1,
        effect: { defense: 3, hp: 15 },
        minRealm: RealmType.GoldenCore,
      },
      {
        id: 'shop-weapon-immortal',
        name: '仙剑·诛仙',
        type: ItemType.Weapon,
        description: '传说中的仙剑，一剑可诛仙，威力达到极致。',
        rarity: '仙品',
        price: 200000,
        sellPrice: 6000,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Weapon,
        effect: { attack: 10000, defense: 2000, hp: 5000 },
        minRealm: RealmType.SpiritSevering,
      },
      {
        id: 'shop-armor-immortal',
        name: '仙甲·不灭',
        type: ItemType.Armor,
        description: '传说中的仙甲，防御力达到极致，几乎不灭。',
        rarity: '仙品',
        price: 18000,
        sellPrice: 5400,
        isEquippable: true,
        equipmentSlot: EquipmentSlot.Chest,
        effect: { defense: 800, hp: 2000, attack: 100 },
        minRealm: RealmType.SpiritSevering,
      },
    ],
  },
  {
    id: 'shop-blackmarket',
    name: '黑市',
    type: ShopType.BlackMarket,
    description: '神秘的黑市，售卖各种稀有物品，价格昂贵但品质极高。',
    items: [], // 物品通过 generateShopItems 动态生成
    refreshCost: 1000, // 刷新费用
    refreshCooldown: 5 * 60 * 1000, // 5分钟冷却
  },
  {
    id: 'shop-limitedtime',
    name: '限时商店',
    type: ShopType.LimitedTime,
    description: '每日限时特价商店，商品种类丰富，价格优惠。',
    items: [], // 物品通过 generateShopItems 动态生成
    discount: 0.2, // 20%折扣
    refreshCooldown: 24 * 60 * 60 * 1000, // 24小时刷新
  },
  {
    id: 'shop-reputation',
    name: '声望商店',
    type: ShopType.Reputation,
    description: '需要声望值才能进入的商店，售卖传承相关的珍贵物品。',
    items: [], // 物品通过 generateShopItems 动态生成
    reputationRequired: 100, // 需要100声望值
  },
];