/**
 * 天赋称号系统相关常量
 */

import { Talent, Title, TitleSetEffect, EncounterEvent, ExplorationLocation, Achievement, RealmType } from '../types';

export const TALENTS: Talent[] = [
  // 普通天赋（3个）
  {
    id: 'talent-ordinary',
    name: '凡体',
    description: '普通的修仙资质，没有任何特殊加成。',
    rarity: '普通',
    effects: {},
  },
  {
    id: 'talent-strong-body',
    name: '强健体魄',
    description: '身体比常人强壮一些，气血略微提升。',
    rarity: '普通',
    effects: { hp: 50 },
  },
  {
    id: 'talent-quick-learner',
    name: '悟性尚可',
    description: '学习能力稍强，修炼速度略微提升。',
    rarity: '普通',
    effects: { expRate: 0.05 },
  },

  // 稀有天赋（8个）
  {
    id: 'talent-spirit-root',
    name: '灵根',
    description: '拥有灵根，修炼速度提升10%。',
    rarity: '稀有',
    effects: { expRate: 0.1 },
  },
  {
    id: 'talent-iron-bone',
    name: '铁骨',
    description: '骨骼坚硬，防御力提升。',
    rarity: '稀有',
    effects: { defense: 30, physique: 20 },
  },
  {
    id: 'talent-sharp-blade',
    name: '利刃',
    description: '天生适合使用武器，攻击力提升。',
    rarity: '稀有',
    effects: { attack: 40 },
  },
  {
    id: 'talent-spirit-sense',
    name: '神识敏锐',
    description: '神识天生敏锐，神识和速度提升。',
    rarity: '稀有',
    effects: { spirit: 25, speed: 15 },
  },
  {
    id: 'talent-vitality',
    name: '生机勃勃',
    description: '生命力旺盛，气血上限大幅提升。',
    rarity: '稀有',
    effects: { hp: 150, physique: 15 },
  },
  {
    id: 'talent-fast-cultivation',
    name: '修炼奇才',
    description: '修炼天赋出众，修炼速度提升15%。',
    rarity: '稀有',
    effects: { expRate: 0.15 },
  },
  {
    id: 'talent-lucky',
    name: '小有气运',
    description: '运气不错，幸运值提升。',
    rarity: '稀有',
    effects: { luck: 20 },
  },
  {
    id: 'talent-balanced',
    name: '均衡发展',
    description: '各项属性均衡提升。',
    rarity: '稀有',
    effects: {
      attack: 20,
      defense: 20,
      hp: 80,
      spirit: 15,
      physique: 15,
      speed: 10,
    },
  },

  // 传说天赋（6个）
  {
    id: 'talent-immortal-body',
    name: '仙体',
    description: '天生仙体，气血和防御大幅提升。',
    rarity: '传说',
    effects: { hp: 200, defense: 50 },
  },
  {
    id: 'talent-sword-heart',
    name: '剑心',
    description: '天生剑心，攻击力大幅提升。',
    rarity: '传说',
    effects: { attack: 100 },
  },
  {
    id: 'talent-thunder-body',
    name: '雷体',
    description: '拥有雷属性体质，攻击和速度大幅提升。',
    rarity: '传说',
    effects: { attack: 80, speed: 40, spirit: 30 },
  },
  {
    id: 'talent-dragon-blood',
    name: '龙血',
    description: '体内流淌着龙族血脉，气血和体魄大幅提升。',
    rarity: '传说',
    effects: { hp: 300, physique: 50, defense: 40 },
  },
  {
    id: 'talent-genius',
    name: '修炼天才',
    description: '修炼天赋绝佳，修炼速度大幅提升。',
    rarity: '传说',
    effects: { expRate: 0.25, spirit: 40 },
  },
  {
    id: 'talent-blessed',
    name: '天眷之人',
    description: '受天道眷顾，幸运值和修炼速度提升。',
    rarity: '传说',
    effects: { luck: 35, expRate: 0.15 },
  },

  // 仙品天赋（3个）
  {
    id: 'talent-lucky-star',
    name: '天运之子',
    description: '受天道眷顾，幸运值大幅提升，更容易遇到奇遇。',
    rarity: '仙品',
    effects: { luck: 50, expRate: 0.2 },
  },
  {
    id: 'talent-immortal-king',
    name: '仙王转世',
    description: '疑似仙王转世，各项属性大幅提升，修炼速度极快。',
    rarity: '仙品',
    effects: {
      attack: 150,
      defense: 100,
      hp: 400,
      spirit: 60,
      physique: 60,
      speed: 50,
      expRate: 0.3,
    },
  },
  {
    id: 'talent-chaos-body',
    name: '混沌之体',
    description: '拥有传说中的混沌之体，所有属性全面提升，修炼速度极快。',
    rarity: '仙品',
    effects: {
      attack: 120,
      defense: 80,
      hp: 350,
      spirit: 50,
      physique: 50,
      speed: 40,
      expRate: 0.25,
      luck: 30,
    },
  },
];

// --- 角色系统：称号 ---
export const TITLES: Title[] = [
  {
    id: 'title-novice',
    name: '初入仙途',
    description: '刚刚踏入修仙之路的新人。',
    requirement: '初始称号',
    effects: {},
  },
  {
    id: 'title-foundation',
    name: '筑基修士',
    description: '成功筑基，正式踏入修仙门槛。',
    requirement: '达到筑基期',
    effects: { attack: 10, defense: 5 },
  },
  {
    id: 'title-golden-core',
    name: '金丹真人',
    description: '凝聚金丹，已是修仙界的中流砥柱。',
    requirement: '达到金丹期',
    effects: { attack: 50, defense: 25, hp: 200 },
  },
  {
    id: 'title-nascent-soul',
    name: '元婴老祖',
    description: '修成元婴，可称一方老祖。',
    requirement: '达到元婴期',
    effects: { attack: 200, defense: 100, hp: 1000 },
  },
  {
    id: 'title-immortal',
    name: '飞升仙人',
    description: '渡劫飞升，已是真正的仙人。',
    requirement: '达到渡劫飞升',
    category: 'cultivation',
    rarity: '仙品',
    effects: { attack: 1000, defense: 500, hp: 5000, expRate: 0.3 },
  },
  // 战斗类称号
  {
    id: 'title-warrior',
    name: '战士',
    description: '在战斗中展现出色实力。',
    requirement: '击败10个敌人',
    category: 'combat',
    rarity: '普通',
    setGroup: 'warrior',
    effects: { attack: 15, defense: 5 },
  },
  {
    id: 'title-slayer',
    name: '屠戮者',
    description: '击败大量敌人的战士。',
    requirement: '击败50个敌人',
    category: 'combat',
    rarity: '稀有',
    setGroup: 'warrior',
    effects: { attack: 50, defense: 20, hp: 100 },
  },
  {
    id: 'title-champion',
    name: '战神',
    description: '战无不胜的绝世强者。',
    requirement: '击败100个敌人',
    category: 'combat',
    rarity: '传说',
    setGroup: 'warrior',
    effects: { attack: 150, defense: 75, hp: 500, speed: 20 },
  },
  // 探索类称号
  {
    id: 'title-explorer',
    name: '探索者',
    description: '对未知世界充满好奇。',
    requirement: '完成20次历练',
    category: 'exploration',
    rarity: '普通',
    setGroup: 'explorer',
    effects: { spirit: 10, luck: 5 },
  },
  {
    id: 'title-adventurer',
    name: '冒险家',
    description: '历经无数冒险的探险者。',
    requirement: '完成50次历练',
    category: 'exploration',
    rarity: '稀有',
    setGroup: 'explorer',
    effects: { spirit: 30, luck: 15, expRate: 0.1 },
  },
  {
    id: 'title-traveler',
    name: '游历者',
    description: '走遍天下的旅人。',
    requirement: '完成100次历练',
    category: 'exploration',
    rarity: '传说',
    setGroup: 'explorer',
    effects: { spirit: 80, luck: 30, expRate: 0.15, speed: 15 },
  },
  // 收集类称号
  {
    id: 'title-collector',
    name: '收藏家',
    description: '喜欢收集各种物品。',
    requirement: '收集10种物品',
    category: 'collection',
    rarity: '普通',
    setGroup: 'collector',
    effects: { luck: 10 },
  },
  {
    id: 'title-hoarder',
    name: '囤积者',
    description: '拥有大量收藏品。',
    requirement: '收集30种物品',
    category: 'collection',
    rarity: '稀有',
    setGroup: 'collector',
    effects: { luck: 25, spirit: 20 },
  },
  {
    id: 'title-treasurer',
    name: '珍宝收藏家',
    description: '拥有无数珍稀收藏品。',
    requirement: '收集50种物品',
    category: 'collection',
    rarity: '传说',
    setGroup: 'collector',
    effects: { luck: 50, spirit: 50, expRate: 0.1 },
  },
  // 特殊类称号
  {
    id: 'title-hermit',
    name: '隐士',
    description: '长期闭关修炼的隐士。',
    requirement: '完成100次打坐',
    category: 'cultivation',
    rarity: '稀有',
    effects: { expRate: 0.2, spirit: 40, physique: 30 },
  },
  {
    id: 'title-alchemist',
    name: '炼丹大师',
    description: '精通炼丹之术。',
    requirement: '炼制20次丹药',
    category: 'special',
    rarity: '稀有',
    effects: { spirit: 30, luck: 15 },
  },
  {
    id: 'title-sect-master',
    name: '宗门主事',
    description: '担任过宗门长老。',
    requirement: '达到长老职位',
    category: 'special',
    rarity: '传说',
    effects: { attack: 100, defense: 100, spirit: 50, expRate: 0.15 },
  },
];

// 称号套装效果
export const TITLE_SET_EFFECTS: TitleSetEffect[] = [
  {
    setName: '战士套装',
    titles: ['title-warrior', 'title-slayer', 'title-champion'],
    description: '佩戴所有战士称号，获得强大的战斗加成',
    effects: {
      attack: 100,
      defense: 50,
      hp: 300,
      speed: 10,
    },
  },
  {
    setName: '探索者套装',
    titles: ['title-explorer', 'title-adventurer', 'title-traveler'],
    description: '佩戴所有探索者称号，提升探索收益',
    effects: {
      spirit: 50,
      luck: 40,
      expRate: 0.2,
      speed: 15,
    },
  },
  {
    setName: '收藏家套装',
    titles: ['title-collector', 'title-hoarder', 'title-treasurer'],
    description: '佩戴所有收藏家称号，大幅提升幸运值',
    effects: {
      luck: 80,
      spirit: 60,
      expRate: 0.15,
    },
  },
];

// --- 奇遇系统 ---
export const ENCOUNTER_EVENTS: EncounterEvent[] = [
  {
    id: 'encounter-herb',
    name: '发现灵草',
    description: '你在山间发现了一株珍贵的灵草。',
    rarity: '普通',
    triggerChance: 0.3,
    rewards: {
      exp: 20,
      items: [{ name: '聚灵草', rarity: '普通', quantity: 1 }],
    },
  },
  {
    id: 'encounter-spirit-stone',
    name: '灵石矿脉',
    description: '你意外发现了一处小型灵石矿脉。',
    rarity: '稀有',
    triggerChance: 0.15,
    rewards: {
      spiritStones: 100,
      exp: 50,
    },
  },
  {
    id: 'encounter-ancient-cave',
    name: '古修士洞府',
    description: '你发现了一处古修士遗留的洞府，获得了珍贵的传承。',
    rarity: '传说',
    triggerChance: 0.05,
    minRealm: RealmType.Foundation,
    requirements: { minLuck: 30 },
    rewards: {
      exp: 500,
      spiritStones: 500,
      items: [{ name: '上古功法残卷', rarity: '传说', quantity: 1 }],
    },
  },
  {
    id: 'encounter-immortal-herb',
    name: '万年仙草',
    description: '你遇到了传说中的万年仙草，这是天大的机缘！',
    rarity: '仙品',
    triggerChance: 0.01,
    minRealm: RealmType.GoldenCore,
    requirements: { minLuck: 50 },
    rewards: {
      exp: 2000,
      items: [{ name: '万年仙草', rarity: '仙品', quantity: 1 }],
    },
  },
];

// --- 探索系统 ---
export const EXPLORATION_LOCATIONS: ExplorationLocation[] = [
  {
    id: 'explore-forest',
    name: '迷雾森林',
    description: '常年被迷雾笼罩的森林，隐藏着许多秘密。',
    minRealm: RealmType.QiRefining,
    cost: 20,
    riskLevel: '低',
    eventTypes: ['normal', 'lucky'],
  },
  {
    id: 'explore-mountain',
    name: '天柱山',
    description: '高耸入云的山峰，传说有仙人居住。',
    minRealm: RealmType.Foundation,
    cost: 50,
    riskLevel: '中',
    eventTypes: ['normal', 'lucky'],
    specialEncounters: ['encounter-ancient-cave'],
  },
  {
    id: 'explore-abyss',
    name: '无底深渊',
    description: '深不见底的深渊，危险与机遇并存。',
    minRealm: RealmType.GoldenCore,
    cost: 200,
    riskLevel: '高',
    eventTypes: ['normal', 'lucky', 'secret_realm'],
    specialEncounters: ['encounter-immortal-herb'],
  },
];

// --- 成就系统 ---
export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-step',
    name: '第一步',
    description: '完成第一次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'custom', value: 1, target: 'meditate' },
    reward: { exp: 50, spiritStones: 10 },
    rarity: '普通',
  },
  {
    id: 'ach-foundation',
    name: '筑基成功',
    description: '突破到筑基期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.Foundation },
    reward: { exp: 500, spiritStones: 200, titleId: 'title-foundation' },
    rarity: '稀有',
  },
  {
    id: 'ach-golden-core',
    name: '金丹大道',
    description: '突破到金丹期',
    category: 'cultivation',
    requirement: { type: 'realm', value: 1, target: RealmType.GoldenCore },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-golden-core' },
    rarity: '传说',
  },
  {
    id: 'ach-first-kill',
    name: '初战告捷',
    description: '在历练中击败第一个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 1 },
    reward: { exp: 100, spiritStones: 50 },
    rarity: '普通',
  },
  {
    id: 'ach-killer-10',
    name: '十人斩',
    description: '击败10个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 10 },
    reward: { exp: 200, spiritStones: 100, titleId: 'title-warrior' },
    rarity: '普通',
  },
  {
    id: 'ach-killer-50',
    name: '百战不殆',
    description: '击败50个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 50 },
    reward: { exp: 1000, spiritStones: 500, titleId: 'title-slayer' },
    rarity: '稀有',
  },
  {
    id: 'ach-killer-100',
    name: '千人斩',
    description: '击败100个敌人',
    category: 'combat',
    requirement: { type: 'kill', value: 100 },
    reward: { exp: 3000, spiritStones: 1500, titleId: 'title-champion' },
    rarity: '传说',
  },
  {
    id: 'ach-collector',
    name: '收藏家',
    description: '收集10种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 10 },
    reward: { exp: 300, spiritStones: 200, titleId: 'title-collector' },
    rarity: '稀有',
  },
  {
    id: 'ach-collector-20',
    name: '物品收藏家',
    description: '收集20种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 20 },
    reward: { exp: 500, spiritStones: 300, titleId: 'title-hoarder' },
    rarity: '稀有',
  },
  {
    id: 'ach-collector-50',
    name: '收藏大师',
    description: '收集50种不同的物品',
    category: 'collection',
    requirement: { type: 'collect', value: 50 },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-treasurer' },
    rarity: '传说',
  },
  {
    id: 'ach-adventure-20',
    name: '历练新手',
    description: '完成20次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 20 },
    reward: { exp: 300, spiritStones: 150, titleId: 'title-explorer' },
    rarity: '普通',
  },
  {
    id: 'ach-adventure-50',
    name: '冒险达人',
    description: '完成50次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 50 },
    reward: { exp: 800, spiritStones: 400, titleId: 'title-adventurer' },
    rarity: '稀有',
  },
  {
    id: 'ach-adventure-100',
    name: '历练老手',
    description: '完成100次历练',
    category: 'exploration',
    requirement: { type: 'adventure', value: 100 },
    reward: { exp: 1500, spiritStones: 800, titleId: 'title-traveler' },
    rarity: '稀有',
  },
  {
    id: 'ach-meditate-100',
    name: '道心坚定',
    description: '完成100次打坐修炼',
    category: 'cultivation',
    requirement: { type: 'meditate', value: 100 },
    reward: { exp: 2000, spiritStones: 1000, titleId: 'title-hermit' },
    rarity: '传说',
  },
  {
    id: 'ach-equip-5',
    name: '装备齐全',
    description: '装备5件物品',
    category: 'collection',
    requirement: { type: 'equip', value: 5 },
    reward: { exp: 200, spiritStones: 100 },
    rarity: '普通',
  },
  {
    id: 'ach-pet-1',
    name: '灵宠伙伴',
    description: '获得第一个灵宠',
    category: 'special',
    requirement: { type: 'pet', value: 1 },
    reward: { exp: 500, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-pet-3',
    name: '灵宠大师',
    description: '获得3个灵宠',
    category: 'special',
    requirement: { type: 'pet', value: 3 },
    reward: { exp: 1500, spiritStones: 800 },
    rarity: '传说',
  },
  {
    id: 'ach-recipe-5',
    name: '丹道入门',
    description: '解锁5个丹方',
    category: 'collection',
    requirement: { type: 'recipe', value: 5 },
    reward: { exp: 400, spiritStones: 200 },
    rarity: '稀有',
  },
  {
    id: 'ach-art-3',
    name: '功法初成',
    description: '学习3种功法',
    category: 'cultivation',
    requirement: { type: 'art', value: 3 },
    reward: { exp: 600, spiritStones: 300 },
    rarity: '稀有',
  },
  {
    id: 'ach-art-10',
    name: '功法大成',
    description: '学习10种功法',
    category: 'cultivation',
    requirement: { type: 'art', value: 10 },
    reward: { exp: 3000, spiritStones: 1500 },
    rarity: '传说',
  },
  {
    id: 'ach-breakthrough-5',
    name: '突破达人',
    description: '完成5次突破',
    category: 'cultivation',
    requirement: { type: 'breakthrough', value: 5 },
    reward: { exp: 1000, spiritStones: 500 },
    rarity: '稀有',
  },
  {
    id: 'ach-secret-realm-5',
    name: '秘境探索者',
    description: '进入5次秘境',
    category: 'exploration',
    requirement: { type: 'secret_realm', value: 5 },
    reward: { exp: 2000, spiritStones: 1000 },
    rarity: '传说',
  },
  {
    id: 'ach-lottery-10',
    name: '抽奖新手',
    description: '进行10次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 10 },
    reward: { exp: 300, spiritStones: 200 },
    rarity: '普通',
  },
  {
    id: 'ach-lottery-50',
    name: '抽奖达人',
    description: '进行50次抽奖',
    category: 'special',
    requirement: { type: 'lottery', value: 50 },
    reward: { exp: 2000, spiritStones: 1500 },
    rarity: '稀有',
  },
  {
    id: 'ach-alchemy-20',
    name: '炼丹宗师',
    description: '成功炼制20次丹药',
    category: 'special',
    requirement: { type: 'custom', value: 20, target: 'alchemy' },
    reward: { exp: 1000, spiritStones: 1000, titleId: 'title-alchemist' },
    rarity: '传说',
  },
  {
    id: 'ach-sect-master',
    name: '宗门砥柱',
    description: '在宗门内晋升至长老或以上职位',
    category: 'special',
    requirement: { type: 'custom', value: 1, target: 'sect_elder' },
    reward: { exp: 2000, spiritStones: 2000, titleId: 'title-sect-master' },
    rarity: '传说',
  },
];
